exclude = [
    "migrations/",
    "node_modules/",
    "__pycache__/",
]

fix = true

line-length = 88

lint.select = [
    "I001",
    "F401",
    "F403",
]

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-third-party = ["pytest"]
known-local-folder = ["gendiff"]
