name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-dev
          poetry show  # Проверка установленных зависимостей

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest  # Запуск тестов через Poetry
          poetry run coverage xml -o coverage.xml  # Генерация отчета

      - name: Upload coverage to Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-reporter
          chmod +x cc-reporter
          ./cc-reporter before-build
          ./cc-reporter format-coverage coverage.xml --input-type coverage.py
          ./cc-reporter upload-coverage
